[package]
authors = ["Alex Moon <alex@moonspot.org>"]
description = "Bluetooth HCI data types"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "bt-hci"
repository = "https://github.com/alexmoon/bt-hci"
version = "0.1.0"

[features]
async = ["embedded-io/async"]

[dependencies]
defmt = { version = "0.3", optional = true }
embedded-io = "0.4.0"
heapless = "0.7.16"
log = { version = "0.4.11", optional = true }
